{{- range $name, $cfg := .Values.agents }}
{{- if $cfg.discord.botToken }}
{{- $d := dict "ctx" $ "agent" $name "cfg" $cfg }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agent-broker.agentFullname" $d }}
  labels:
    {{- include "agent-broker.labels" $d | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  discord-bot-token: {{ $cfg.discord.botToken | b64enc | quote }}
{{- end }}
{{- end }}
